
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Nav from "./components/navigation/page";
import Footer from "./components/footer/page";
import FlyonuiScript from "./components/FlyonuiScript";


import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative overflow-x-hidden overflow-y-auto max-h-screen">
          <Nav />
          {children}
          <Footer />
        </div>
        <FlyonuiScript />
      </body>
    </html>
  );
}
