
import type { Metadata } from "next";
import { Encode_Sans_Condensed, Anton, Inter } from "next/font/google";
import Nav from "./components/navigation/page";
import Footer from "./components/footer/page";
import FlyonuiScript from "./components/FlyonuiScript";


import "./globals.css";

const encodeSansCondensed = Encode_Sans_Condensed({
  variable: "--font-encode-sans-condensed",
  subsets: ["latin"],
  weight: "400"
});
const anton = Anton({
  variable: "--font-anton",
  subsets: ["latin"],
  weight: "400"
});

const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: "500"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interFont.variable} ${interFont.variable} antialiased`}
      >
        <div className="relative overflow-x-hidden overflow-y-auto max-h-screen">
          <Nav />
          {children}
          <Footer />
        </div>
        <FlyonuiScript />
      </body>
    </html>
  );
}
